"use client"
import AOSContainer from '@/components/AOS/AOSContainer'
import Layout from '@/components/shared/layout/Layout'
import TransformModal from '@/components/shared/transformModal/TransformModal'
import './globals.css'
import { useEffect, useRef, useState } from 'react'
import React from 'react'
import {NextIntlClientProvider} from 'next-intl';
import {notFound} from 'next/navigation';

export const HandleOpenContext = React.createContext<any>("test");
// export const metadata = {
//   title: 'Navus Lab',
//   description: 'Generated by Navus Lab',
// }

export function generateStaticParams() {
  return [{locale: 'en'}, {locale: 'de'}, {locale: 'ar'}];
}

export default function RootLayout({
  children,
  params:{locale},
}: {
  children: React.ReactNode,
  params: any,
}) {
  let messagesRef:any = useRef();
  try {
    useEffect(() => {
      messagesRef.current = (import(`@/messages/${locale}.json`)).then((res)=>res.default);
    }, [locale]);

  } catch (error) {
    notFound();
  }
  const [open, setOpen] = useState(false);
  const handleOpen = () => setOpen(true);
  const handleClose = () => setOpen(false);
  return (
    <html lang={locale}>
      <body>
      <AOSContainer>
      <HandleOpenContext.Provider value={handleOpen}>
        <Layout>
        <NextIntlClientProvider locale={locale} messages={messagesRef.current}>
          {children}
         <TransformModal open={open} handleClose={handleClose} />
        </NextIntlClientProvider>
      </Layout>
      </HandleOpenContext.Provider>
      </AOSContainer>
      </body>
    </html>
  )
}
