import './globals.css'
import React from 'react'
import {NextIntlClientProvider} from 'next-intl';
import {notFound} from 'next/navigation';
import AppLayout from './app.layput';
import {dir} from 'i18next';

export const metadata = {
  title: 'Navus Lab',
  description: 'Generated by Navus Lab',
}

export function generateStaticParams() {
  return [{locale: 'en'}, {locale: 'de'}, {locale: 'ar'}];
}

export default async function RootLayout({
  children,
  params:{locale},
}: {
  children: React.ReactNode,
  params: any,
}) {
  let messages
  try {
    messages = (await import(`../../messages/${locale}.json`)).default;
  } catch (error) {
    notFound();
  }
  return (
    <html lang={locale} dir={dir(locale)}>
      <body>
        <NextIntlClientProvider locale={locale} messages={messages}>
          <AppLayout>
          {children}
          </AppLayout>
        </NextIntlClientProvider>
      </body>
    </html>
  )
}
