"use client"
import AOSContainer from '@/components/AOS/AOSContainer'
import Layout from '@/components/shared/layout/Layout'
import TransformModal from '@/components/shared/transformModal/TransformModal'
import './globals.css'
import { useState } from 'react'
import React from 'react'
export const HandleOpenContext = React.createContext<any>(null);


// export const metadata = {
//   title: 'Navus Lab',
//   description: 'Generated by Navus Lab',
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const [open, setOpen] = useState(false);
  const handleOpen = () => setOpen(true);
  const handleClose = () => setOpen(false);
  return (
    <html lang="en">
      <body>
      <AOSContainer>
      <HandleOpenContext.Provider value={handleOpen}>
        <Layout>
          {children}
         <TransformModal open={open} handleClose={handleClose} />
      </Layout>
      </HandleOpenContext.Provider>
      </AOSContainer>
      </body>
    </html>
  )
}
